### ISSUE TITLE
Static route to regex table

### ISSUE THREAD

**Issue by edimoldovan** [benhoyt/go-routing#2]
HI,

Great post about various routing options: https://benhoyt.com/writings/go-routing/#regex-table
How would you suggest add a static route to the routing table?

ed

**Comment by benhoyt** [comment]
Hi Ed, here's one way:

```go
var staticServer = http.FileServer(http.Dir("/tmp"))

var routes = []route{
	newRoute("GET", "/", home),
	...
	newRoute("GET", "/static/.*", http.StripPrefix("/static/", staticServer).ServeHTTP),
}
```

Does that work for you?
