### ISSUE TITLE
websocket route

### ISSUE THREAD

**Issue by edimoldovan** [benhoyt/go-routing#3]
Hi Ben,

It's me again :)
I am trying to to implement a websocket route for reloading the page in the browser when the server restarts, for now using this library: golang.org/x/net/websocket
Same question as before, how would you implement a websocket route with the same regex table approach? https://benhoyt.com/writings/go-routing/#regex-table

ed

**Comment by benhoyt** [comment]
@edimoldovan Assuming `CreateRoute` takes an `http.HandlerFunc` as its third argument like `newRoute` did, you don't actually need to convert to an `http.HandlerFunc` -- the `websocket.Handler(Live).ServeHTTP` is already an `http.HandlerFunc`, so you can just do:

```go
// if CreateRoute takes an http.HandlerFunc:
CreateRoute("GET", "/live", websocket.Handler(Live).ServeHTTP)
// or, if CreateRoute takes an http.Handler:
CreateRoute("GET", "/live", websocket.Handler(Live))
```
