### ISSUE TITLE
add license?

### ISSUE THREAD

**Issue by komuw** [benhoyt/go-routing#5]
Hello, 

I would like to re-use some of the code you have in here to write tests for a muxer that I have been [working on](https://pkg.go.dev/github.com/komuw/ong/mux). 
Do you mind adding a license to this repository? 

Thanks.

**Comment by benhoyt** [comment]
Added: https://github.com/benhoyt/go-routing/blob/master/LICENSE.txt

I presume you're aware of the new pattern-based routing features in `http.ServeMux` in Go 1.22?
